# Setup
name:         Forseti's Blog
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
# markdown: kramdown
# Google Analytics
google_analytics: G-QTJ4C2S4VR
